# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_ts <- function(mtx) {
    .Call(`_sitsfeats_max_ts`, mtx)
}

min_ts <- function(mtx) {
    .Call(`_sitsfeats_min_ts`, mtx)
}

mean_ts <- function(mtx) {
    .Call(`_sitsfeats_mean_ts`, mtx)
}

median_ts <- function(mtx) {
    .Call(`_sitsfeats_median_ts`, mtx)
}

sum_ts <- function(mtx) {
    .Call(`_sitsfeats_sum_ts`, mtx)
}

std_ts <- function(mtx) {
    .Call(`_sitsfeats_std_ts`, mtx)
}

skew_ts <- function(mtx) {
    .Call(`_sitsfeats_skew_ts`, mtx)
}

kurt_ts <- function(mtx) {
    .Call(`_sitsfeats_kurt_ts`, mtx)
}

amplitude_ts <- function(mtx) {
    .Call(`_sitsfeats_amplitude_ts`, mtx)
}

fslope_ts <- function(mtx) {
    .Call(`_sitsfeats_fslope_ts`, mtx)
}

abs_sum_ts <- function(mtx) {
    .Call(`_sitsfeats_abs_sum_ts`, mtx)
}

amd_ts <- function(mtx) {
    .Call(`_sitsfeats_amd_ts`, mtx)
}

mse_ts <- function(mtx) {
    .Call(`_sitsfeats_mse_ts`, mtx)
}

fqr_ts <- function(mtx) {
    .Call(`_sitsfeats_fqr_ts`, mtx)
}

tqr_ts <- function(mtx) {
    .Call(`_sitsfeats_tqr_ts`, mtx)
}

sqr_ts <- function(mtx) {
    .Call(`_sitsfeats_sqr_ts`, mtx)
}

iqr_ts <- function(mtx) {
    .Call(`_sitsfeats_iqr_ts`, mtx)
}

calculate_vec <- function(timeseries) {
    .Call(`_sitsfeats_calculate_vec`, timeseries)
}

chn <- function(x) {
    .Call(`_sitsfeats_chn`, x)
}

calc_bbox_fast <- function(pts) {
    .Call(`_sitsfeats_calc_bbox_fast`, pts)
}

get_seasons_fast <- function(pts, colsize) {
    .Call(`_sitsfeats_get_seasons_fast`, pts, colsize)
}

polytopleft <- function(bbox_pts) {
    .Call(`_sitsfeats_polytopleft`, bbox_pts)
}

polytopright <- function(bbox_pts) {
    .Call(`_sitsfeats_polytopright`, bbox_pts)
}

polybottomleft <- function(bbox_pts) {
    .Call(`_sitsfeats_polybottomleft`, bbox_pts)
}

polybottomright <- function(bbox_pts) {
    .Call(`_sitsfeats_polybottomright`, bbox_pts)
}

reptest <- function(x, time) {
    .Call(`_sitsfeats_reptest`, x, time)
}

calculate_vec_v3 <- function(timeseries) {
    .Call(`_sitsfeats_calculate_vec_v3`, timeseries)
}

calculate_vec_v3_id <- function(timeseries) {
    .Call(`_sitsfeats_calculate_vec_v3_id`, timeseries)
}

calc_distance <- function(line, pts_cent) {
    .Call(`_sitsfeats_calc_distance`, line, pts_cent)
}

gr_calc <- function(pts_cent, pts_line, size_col) {
    .Call(`_sitsfeats_gr_calc`, pts_cent, pts_line, size_col)
}

std_np <- function(timeseries) {
    .Call(`_sitsfeats_std_np`, timeseries)
}

teste_linspace <- function(r, len) {
    .Call(`_sitsfeats_teste_linspace`, r, len)
}

linspace_vec <- function(timeseries) {
    .Call(`_sitsfeats_linspace_vec`, timeseries)
}

calc_angle <- function(timeseries) {
    .Call(`_sitsfeats_calc_angle`, timeseries)
}

calc_csi <- function(line_length, poly_area) {
    .Call(`_sitsfeats_calc_csi`, line_length, poly_area)
}

