# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_ts <- function(mtx) {
    .Call(`_sitsfeats_max_ts`, mtx)
}

min_ts <- function(mtx) {
    .Call(`_sitsfeats_min_ts`, mtx)
}

mean_ts <- function(mtx) {
    .Call(`_sitsfeats_mean_ts`, mtx)
}

median_ts <- function(mtx) {
    .Call(`_sitsfeats_median_ts`, mtx)
}

std_ts <- function(mtx) {
    .Call(`_sitsfeats_std_ts`, mtx)
}

skew_ts <- function(mtx) {
    .Call(`_sitsfeats_skew_ts`, mtx)
}

kurt_ts <- function(mtx) {
    .Call(`_sitsfeats_kurt_ts`, mtx)
}

amplitude_ts <- function(mtx) {
    .Call(`_sitsfeats_amplitude_ts`, mtx)
}

fslope_ts <- function(mtx) {
    .Call(`_sitsfeats_fslope_ts`, mtx)
}

amd_ts <- function(mtx) {
    .Call(`_sitsfeats_amd_ts`, mtx)
}

fqr_ts <- function(mtx) {
    .Call(`_sitsfeats_fqr_ts`, mtx)
}

tqr_ts <- function(mtx) {
    .Call(`_sitsfeats_tqr_ts`, mtx)
}

sqr_ts <- function(mtx) {
    .Call(`_sitsfeats_sqr_ts`, mtx)
}

iqr_ts <- function(mtx) {
    .Call(`_sitsfeats_iqr_ts`, mtx)
}

calculate_vec <- function(timeseries) {
    .Call(`_sitsfeats_calculate_vec`, timeseries)
}

calculate_vec_v2 <- function(timeseries) {
    .Call(`_sitsfeats_calculate_vec_v2`, timeseries)
}

calculate_vec_v3 <- function(timeseries) {
    .Call(`_sitsfeats_calculate_vec_v3`, timeseries)
}

calc_distance <- function(line, pts_cent) {
    .Call(`_sitsfeats_calc_distance`, line, pts_cent)
}

gr_calc <- function(pts_cent, pts_line) {
    .Call(`_sitsfeats_gr_calc`, pts_cent, pts_line)
}

teste_linspace <- function(r, len) {
    .Call(`_sitsfeats_teste_linspace`, r, len)
}

linspace_vec <- function(timeseries) {
    .Call(`_sitsfeats_linspace_vec`, timeseries)
}

calc_angle <- function(timeseries) {
    .Call(`_sitsfeats_calc_angle`, timeseries)
}

calc_csi <- function(line_length, poly_area) {
    .Call(`_sitsfeats_calc_csi`, line_length, poly_area)
}

rcpparma_hello_world <- function() {
    .Call(`_sitsfeats_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_sitsfeats_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_sitsfeats_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_sitsfeats_rcpparma_bothproducts`, x)
}

