# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_calc <- function(mtx) {
    .Call(`_sitsfeats_max_calc`, mtx)
}

min_calc <- function(mtx) {
    .Call(`_sitsfeats_min_calc`, mtx)
}

mean_calc <- function(mtx) {
    .Call(`_sitsfeats_mean_calc`, mtx)
}

median_calc <- function(mtx) {
    .Call(`_sitsfeats_median_calc`, mtx)
}

sum_calc <- function(mtx) {
    .Call(`_sitsfeats_sum_calc`, mtx)
}

std_calc <- function(mtx) {
    .Call(`_sitsfeats_std_calc`, mtx)
}

skew_calc <- function(mtx) {
    .Call(`_sitsfeats_skew_calc`, mtx)
}

kurt_calc <- function(mtx) {
    .Call(`_sitsfeats_kurt_calc`, mtx)
}

amplitude_calc <- function(mtx) {
    .Call(`_sitsfeats_amplitude_calc`, mtx)
}

fslope_calc <- function(mtx) {
    .Call(`_sitsfeats_fslope_calc`, mtx)
}

abs_sum_calc <- function(mtx) {
    .Call(`_sitsfeats_abs_sum_calc`, mtx)
}

amd_calc <- function(mtx) {
    .Call(`_sitsfeats_amd_calc`, mtx)
}

mse_calc <- function(mtx) {
    .Call(`_sitsfeats_mse_calc`, mtx)
}

fqr_calc <- function(mtx) {
    .Call(`_sitsfeats_fqr_calc`, mtx)
}

sqr_calc <- function(mtx) {
    .Call(`_sitsfeats_sqr_calc`, mtx)
}

tqr_calc <- function(mtx) {
    .Call(`_sitsfeats_tqr_calc`, mtx)
}

iqr_calc <- function(mtx) {
    .Call(`_sitsfeats_iqr_calc`, mtx)
}

calc_bbox <- function(pts) {
    .Call(`_sitsfeats_calc_bbox`, pts)
}

get_seasons_fast <- function(pts, colsize) {
    .Call(`_sitsfeats_get_seasons_fast`, pts, colsize)
}

polytopleft <- function(bbox_pts) {
    .Call(`_sitsfeats_polytopleft`, bbox_pts)
}

polytopright <- function(bbox_pts) {
    .Call(`_sitsfeats_polytopright`, bbox_pts)
}

polybottomleft <- function(bbox_pts) {
    .Call(`_sitsfeats_polybottomleft`, bbox_pts)
}

polybottomright <- function(bbox_pts) {
    .Call(`_sitsfeats_polybottomright`, bbox_pts)
}

repvalues <- function(x, time) {
    .Call(`_sitsfeats_repvalues`, x, time)
}

calculate_polar <- function(timeseries) {
    .Call(`_sitsfeats_calculate_polar`, timeseries)
}

calc_distance <- function(line, pts_cent) {
    .Call(`_sitsfeats_calc_distance`, line, pts_cent)
}

gr_calc <- function(pts_cent, pts_line, size_col) {
    .Call(`_sitsfeats_gr_calc`, pts_cent, pts_line, size_col)
}

std_np <- function(timeseries) {
    .Call(`_sitsfeats_std_np`, timeseries)
}

calc_ecc <- function(bboxmat) {
    .Call(`_sitsfeats_calc_ecc`, bboxmat)
}

linspace_vec <- function(timeseries) {
    .Call(`_sitsfeats_linspace_vec`, timeseries)
}

calc_angle <- function(timeseries) {
    .Call(`_sitsfeats_calc_angle`, timeseries)
}

calc_csi <- function(line_length, poly_area) {
    .Call(`_sitsfeats_calc_csi`, line_length, poly_area)
}

